#:schema node_modules/wrangler/config-schema.json
name = "lyricsplus"
main = "src/index-wrangler.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-11-12"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[kv_namespaces]]
binding = "LYRICSPLUS"
id = "cbae51fb39f247c1845b96fe0c2f58aa"
preview_id = "2b3a33b07f21484ba7b4a26222c7a2fc"

[[unsafe.bindings]]
name = "MY_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 100, period = 60 }
